name: Request a new Agent Repo
description: Create a new repo from standard templates (basic agent or agent+tools)
title: "New agent repo: <repo_name>"
labels: ["repo-request"]

body:
  - type: input
    id: repo_name
    attributes:
      label: Repo name
      description: New repository name to create under your account
      placeholder: uc-001-care-mgmt-agent
    validations:
      required: true

  - type: dropdown
    id: template_type
    attributes:
      label: Template type
      description: Choose which scaffold to use
      options:
        - BASIC_AGENT (tmpl-python-langgraph-single)
        - AGENT_WITH_TOOLS (tmpl-python-langgraph-agent-tools)
      default: 1
    validations:
      required: true

  - type: dropdown
    id: visibility
    attributes:
      label: Repo visibility
      options:
        - PUBLIC
        - PRIVATE
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **What happens next**
        - A GitHub Action will read this issue
        - It will create a new repo from the selected template
        - It will comment back with the created repo name
